
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE) VALUES (1, FLOOR(DBMS_RANDOM.VALUE(201, 230)), TRUNC(SYSDATE - DBMS_RANDOM.VALUE(0, 365)));
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE) VALUES (2, FLOOR(DBMS_RANDOM.VALUE(201, 230)), TRUNC(SYSDATE - DBMS_RANDOM.VALUE(0, 365)));
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE) VALUES (3, FLOOR(DBMS_RANDOM.VALUE(201, 230)), TRUNC(SYSDATE - DBMS_RANDOM.VALUE(0, 365)));
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE) VALUES (4, FLOOR(DBMS_RANDOM.VALUE(201, 230)), TRUNC(SYSDATE - DBMS_RANDOM.VALUE(0, 365)));
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE) VALUES (5, FLOOR(DBMS_RANDOM.VALUE(201, 230)), TRUNC(SYSDATE - DBMS_RANDOM.VALUE(0, 365)));
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE) VALUES (6, FLOOR(DBMS_RANDOM.VALUE(201, 230)), TRUNC(SYSDATE - DBMS_RANDOM.VALUE(0, 365)));
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE) VALUES (7, FLOOR(DBMS_RANDOM.VALUE(201, 230)), TRUNC(SYSDATE - DBMS_RANDOM.VALUE(0, 365)));
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE) VALUES (8, FLOOR(DBMS_RANDOM.VALUE(201, 230)), TRUNC(SYSDATE - DBMS_RANDOM.VALUE(0, 365)));
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE) VALUES (9, FLOOR(DBMS_RANDOM.VALUE(201, 230)), TRUNC(SYSDATE - DBMS_RANDOM.VALUE(0, 365)));
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE) VALUES (10, FLOOR(DBMS_RANDOM.VALUE(201, 230)), TRUNC(SYSDATE - DBMS_RANDOM.VALUE(0, 365)));
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE) VALUES (11, FLOOR(DBMS_RANDOM.VALUE(201, 230)), TRUNC(SYSDATE - DBMS_RANDOM.VALUE(0, 365)));
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE) VALUES (12, FLOOR(DBMS_RANDOM.VALUE(201, 230)), TRUNC(SYSDATE - DBMS_RANDOM.VALUE(0, 365)));
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE) VALUES (13, FLOOR(DBMS_RANDOM.VALUE(201, 230)), TRUNC(SYSDATE - DBMS_RANDOM.VALUE(0, 365)));
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE) VALUES (14, FLOOR(DBMS_RANDOM.VALUE(201, 230)), TRUNC(SYSDATE - DBMS_RANDOM.VALUE(0, 365)));
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE) VALUES (15, FLOOR(DBMS_RANDOM.VALUE(201, 230)), TRUNC(SYSDATE - DBMS_RANDOM.VALUE(0, 365)));
