BEGIN
    FOR rec IN (
        SELECT od.ORDER_ID, od.QUANTITY, o.CUSTOMER_ID
        FROM ORDER_DETAILS od
        JOIN ORDERS o ON od.ORDER_ID = o.ORDER_ID
    )
    LOOP
        UPDATE UGYFELEK
        SET KONYVEKVASAROLVA = KONYVEKVASAROLVA + rec.QUANTITY
        WHERE UGYFELID = rec.CUSTOMER_ID;
    END LOOP;
    COMMIT;
END;